// <auto-generated />
namespace AutomotiveForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedbuildofthemonth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedbuildofthemonth));
        
        string IMigrationMetadata.Id
        {
            get { return "201808021452332_added build of the month"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
