// <auto-generated />
namespace AutomotiveForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class postlike : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postlike));
        
        string IMigrationMetadata.Id
        {
            get { return "201808081830276_post like"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
