// <auto-generated />
namespace AutomotiveForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class created_comment_model_and_controller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(created_comment_model_and_controller));
        
        string IMigrationMetadata.Id
        {
            get { return "201807311828464_created_comment_model_and_controller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
